### ISSUE TITLE
3D Print File P02_Drill_Default.step is Incorrect

### ISSUE THREAD

**Issue by dfife** [0xD0M1M0/ExoMy#1]
3D Print File P02_Drill_Default.step is Incorrect. The file actually prints out the right solar panel. I have converted the .stl version (which is correct) using FreeCAD. I have attached the file. I am not a Cad expert and the fidelity of the file may not be the best. Typically, you would use a .step file over a .stl for a better quality print if you printer is capable of ultra fine quality.  I test printed the converted file on my Bambu Labs X1 Carbon and the quality appeared good to me.
[P02_Drill_Default.zip](https://github.com/0xD0M1M0/ExoMy/files/14469852/P02_Drill_Default.zip)

**Comment by 0xD0M1M0** [comment]
Hello @dfife the attachment vanished. Could you upload it again?

Just for reference: https://github.com/esa-prl/ExoMy/issues/18

**Comment by 0xD0M1M0** [comment]
Fixed in release v1.0.3
