### ISSUE TITLE
Camera does not work with Raspberry Pi 64biit OS

### ISSUE THREAD

**Issue by dfife** [0xD0M1M0/ExoMy#2]
The camera does not work with the current (as of 3/14/2024) build of the Docker image. You need to add some lines to the config.txt file on the Raspberry Pi 64bit (not inside the docker instance). Here are the instructions to add to the software build section of the ExoMy instruction set:

1. Open a terminal session on the Raspberry Pi
2. Edit the config.txt file and add 2 lines.  Run "sudo nano /boot/firmware/config.txt"
3. Comment out the line "camera_auto_detect=1" by placing a "#" in front of the line.
4. Add the following immediately below the line you just commented out:
start_x=1
gpu_mem=128
5. Save and close nano with "ctlr +X" then "y", then Enter
6. Reboot with the command "sudo reboot now"
7. Open a Terminal session again and install cmake by running "sudo apt install cmake"
8. Reboot: "sudo reboot now"
9.  Open a terminal session and test by running "vcgencmd get_camera" You should get a result like: supported=1 detected=1, libcamera interfaces=0

These instructions were built from the Raspberry Pi support forum at https://forums.raspberrypi.com/viewtopic.php?t=323390

**Comment by 0xD0M1M0** [comment]
Thank you @dfife for your input. Steps 7 and 8 are not required (as per my tests). I updated the wiki and moved steps 2 to 5 in a bash command for faster update.

The wiki is now updated to support from the beginning version Bookworm (64-bit) of the Raspberry OS.
