### ISSUE TITLE
Instructions for how to get to the Web Interface are not provided

### ISSUE THREAD

**Issue by dfife** [0xD0M1M0/ExoMy#3]
In the Final Integration, we should give instructions for how to load the web interface from a browser.  Add a line to the Final integration section such as:

To access the web interface while on you home network, goto:
http://ip.of.your.Raspberry_Pi:8000

The IP will vary depending on your home network. The :8000 represents the port you need to connect on. That tells the Raspberry Pi to send this connection to the Docker instance.

**Comment by 0xD0M1M0** [comment]
The instructions are provided in the chapter [Operation Instructions](https://github.com/0xD0M1M0/ExoMy/wiki/Operation-Instructions).

I updated the chapter to make it more clear.
